### ISSUE TITLE
complete backups of tbrc.org configuration

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/library-issues#124]
We need to complete the backing up of browser and exist-db configuration items from the tbrc.org ec2 instance.

The items in `~ec2-user/scripts/backup2tbrcrs3.sh` need to be sync'd to s3 similar to what is being done with the db-backups and logs. The various configuration files and such are needed to rebuild the tbrc.org.

These configuration items don't change often but we need a complete picture of the server configuration.

**Comment by TBRC-Travis** [comment]
I've created ~ec2-user/scripts/ec2Backup.sh which will sync the appropriate config items to s3://data.tbrc.org.  These items will then be synced to RS3 using the Cloud Sync job I have setup there.

Chris, can you review ec2Backup.sh and let me know if there's anything else I need to add?  Once you give it the thumbs up I'll add it to our nightly cronjob.  Thanks!

**Comment by TBRC-Travis** [comment]
I've tested ec2Backup.sh and added it to crontab on the ec2 instance so it runs nightly.  I've verified that the appropriate files have been sent to s3://data.tbrc.org and the corresponding backup on RS3.  If there are further issues please file a separate bug.

**Comment by xristy** [comment]
Thank you very much. I had not ignored your request to review other matters claimed my time.  I now have reviewed and all looks good that is covered in ec2Backup.sh. I'll open another issue to request that the downloads/ directory be added to the ec2Backup.sh since that is where war files and other items get retained.
