### ISSUE TITLE
Nodes count in outline

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#138]
@xristy , Hi Chris, Is they anyway to count the Notes in outline through our website? I am writing a report and wanted to reports nodes of each outline. There are around 20 outlines for this time.

**Comment by karmagongde** [comment]
Please help me how to count nodes in outline. It will be very helpful for us to add in Team Report. Thank you.

**Comment by eroux** [comment]
There are currently 370549 outline nodes

**Comment by karmagongde** [comment]
@eroux Hi Elie, Thank you for whole node counts. 
I have to write a Team Report each month on work done by Cambridge Librarians. 
Therefore, I need to count how many nodes are there in a individual outline created in the month. For that, is there any tools in BDRC website or any script to count nodes in Outline? 
Few weeks ago, below weblink is working and now is not. Is there a newer one?
http://purl.bdrc.io/resource/templates?searchType=Work_outline&R_id=bdr:W12827

**Comment by eroux** [comment]
I'm affraid we can't really know the number of outline nodes that have been modified / created in a period of time... that would be a very difficult thing to do... We can think of something in the next system though.

**Comment by karmagongde** [comment]
@eroux Hi Elie, That link shows the result of whole work number, outline, outline nodes. person, topic etc. of the Year. I need same as http://purl.bdrc.io/query/Work_outline?R_id=bdr:W12827. But returned result 10000 or so. Is it possible to increase the result count in purl.bdrc.io?. Please see the Github ticket #171

**Comment by xristy** [comment]
@karmagongde do you need the node count or a list of all the nodes? I thought you just need the count. If so then we need perhaps a slightly different query that returns counts rather than having to increase the number of results to 10K.

**Comment by karmagongde** [comment]
@xristy I need the node count for checking node in a outline for monthly reporting purpose.

**Comment by xristy** [comment]
So you don't need the list of all the nodes just a single number per Work-with-Outline. I think that the purl.bdrc.io needs a different query. Try:

[Work_outline_count: W12827](http://purl.bdrc.io/query/Work_outline_count?R_id=bdr:W12827)

**Comment by karmagongde** [comment]
I tried Work_outline_count: W12827 and result 1 only. It is not working. 
I like to use purl.bdrc.io if it is possible to increase the result range to 10K.

**Comment by xristy** [comment]
@karmagongde The result is the number of nodes in the outline for W12827, which is what I understood you to say is what you wanted!! You simply supply the RID and you get back a single number which is the number of nodes in the Outline. You don't need a list of 10000 nodes to be able to report that there are 10000 nodes. You just need the single number which is why the query has only one result.

**Comment by karmagongde** [comment]
For instance, nodes in the work number W4PD973, the Returned 500 results. Actually there are way more nodes in W4PD973. Because ranged set in purl.bdrc.io would be 500 only.
Please check the following work number's result. All are same 500.
W4PD973-O8LS28119
W4PD1207-O3CN8814
W1PD95844-O2MS16391

![screen shot 2018-04-06 at 12 24 49 pm](https://user-images.githubusercontent.com/19337852/38432554-d195cfd8-3995-11e8-97f2-81de4c2ff7ce.png)

**Comment by xristy** [comment]
@karmagongde Please run: [Work_outline_count: W4PD973](http://purl.bdrc.io/query/Work_outline_count?R_id=bdr%3AW4PD973).

The answer is: 1265^^http://www.w3.org/2001/XMLSchema#integer. Just ignore the ^^http://www.w3.org/2001/XMLSchema#integer. The number of nodes in W4PD973 is 1265.

The query you should be using is Work_outline_count NOT Work_outline

**Comment by karmagongde** [comment]
@xristy Thank you Chris, Now outline node count is working.
