### ISSUE TITLE
Spreadsheet of folder's list with page count

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#140]
@TBRC-Travis Hi Travis, Could you please generate spreadsheet of the folders list with page count for following folders located at Incoming/scans/Inbox/: 
1-w0029
2-dpal spungs shing par yig cha
3-Zangwen-bod ljongs
4-tshogs shul ba ma nor bu don grub kyi dpe cha pod 14 bzhugs
5-gsar bsnan dpe cha
6-chos bzang gi gsung 'bum
7-byang pa rig 'dzin chen mo'i rnam thar-W21523 (443-570)
8-w# of mixed cases

**Comment by TBRC-Travis** [comment]
Karma, I see you've created a "1. Miscellaneous Folder backlog.ods" in Google Sheets.  Do you want me to add to that spreadsheet or create a new one?

**Comment by TBRC-Travis** [comment]
If you want me to use the existing spreadsheet I could add new tabs for the different folders here so I don't mess up any of the existing work you've done already.

**Comment by karmagongde** [comment]
@TBRC-Travis Please create a new spreadsheet for listed folders only. 1.Miscellaneous Folder backlog is almost done. Adding new tab also make confuse to find the tab. Therefore, it is better for new spreadsheet and please name 2.Miscellaneous backlog. Thank you.

**Comment by TBRC-Travis** [comment]
@karmagongde, here's the new spreadsheet:

https://docs.google.com/spreadsheets/d/1s7V_LLMa_e0J7KCeAARHq669vx78ImhsHBaN9yx4-5c/edit#gid=0

to get the page count to be correct I had to clean up some extraneous files and while I was in the process of that I accidentally deleted "8-w# of mixed cases".  the deletion was mirrored to RS4 as well so unfortunately the files are gone.  Is there any way for you to get these files back from a source hard drive?  I'm so sorry about this.  I've now enabled the "Recycle Bin" feature for Incoming on RS3 and RS4 but this change will only affect future issues like this.

**Comment by TBRC-Travis** [comment]
From Synology Support:

"Unfortunately you are correct, if the recycle bin isn't enabled or you don't have a spare copy on another system the files will be lost. Since Shared Folder Sync is automatic and real time there is currently no way to keep it from mirroring over the deletion. I would suggest having the recycle bin enabled so if a file mistakenly gets deleted you can still recover it."_

**Comment by karmagongde** [comment]
I will check and let you know the deleted "8-w# of mixed cases". Could be a duplicate.

**Comment by karmagongde** [comment]
Travis, Thank you for generating Spreadsheet 2.Miscellaneous backlog. 8-w# of mixed cases folder's images are mostly unclear texts and no need. Therefore, I am closing this ticket.
