### ISSUE TITLE
Please try to convert PDF to word document is possible.

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#142]
Hi, Here is Palpung Sherabling woodblocks prints list. If possible, please convert to Word Document. It will be very useful for librarians to search and outline purpose. Thank you. 
[dpal spungs shing par.pdf](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1675108/dpal.spungs.shing.par.pdf)

**Comment by xristy** [comment]
Nothing I can do with it. It's not Unicode and the resulting Word, docx, is junk.
[dpal.spungs.shing.par.docx](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1675145/dpal.spungs.shing.par.docx)

**Comment by karmagongde** [comment]
Thank you for looking. Its too bad not using unicode font.
