### ISSUE TITLE
W8LS16106 - folders need to be reorganized

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#159]
Please review the following image group directories found here:  Incoming/scans/ReadyToProcess/Mangaram/ReceivedFromMangaram/W8LS16106/sources/cropped/images

W8LS16106-I8LS16123
W8LS16106-I8LS16124
W8LS16106-I8LS16125
W8LS16106-I8LS16126
W8LS16106-I8LS16127
W8LS16106-I8LS16173

Each of these directories contains a folder with multiple directories underneath and I'm wondering if these all actually belong to the same volume or whether they just aren't organized properly.  For example, under W8LS16106-I8LS16123/01_yum there are many directories.  Is that correct?  Please take a look.

**Comment by karmagongde** [comment]
recount has increased the folder numbers. So, old scan request are deleted and created new scan request. All the images are in right folder at same location. Two folders are not yet cropped.
W8LS16106-I8LS31493
W8LS16106-I8LS31531

**Comment by TBRC-Travis** [comment]
Thanks Karma.  This work has been processed and synced.

https://www.tbrc.org/#!rid=W8LS16106
