### ISSUE TITLE
W3CN11633 - folders need to be reorganized

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#160]
Please take a look at the image group directories found here:

Incoming/scans/ReadyToProcess/Miscellaneous-backlog/W3CN11633-(all images need to be cropped and arrange order)

There are many subfolders in these directories that need to be organized properly.  All image folders need to be organized so that they're on the same level with no subfolders.

For example, look at W3CN11633-I3CN11673 which currently contains images in these folders:

1-dpe tshan sna tshogs 659-690~~460p
1-dpe tshan sna tshogs 659-690~~460p/0-BL. kye rdor mngon rtogs yan lag drug pa BW 669/
2-dpe tshan sna tshogs 691-712~~640p/
2-dpe tshan sna tshogs 691-712~~640p/gtsug gtor rnam rgyal ma BW 696/

The two subfolders "0-BL. kye rdor mngon rtogs yan lag drug pa BW 669" and "gtsug gtor rnam rgyal ma BW 696" need to be moved to the same level as the parent folders so there's 4 folders all at the same level and numbered properly (1-xxxxx, 2-xxxxx, 3-xxxxx, 4-xxxxx) so that I know how they need to be ordered.

Please look through all image group folders and arrange the folders accordingly.

**Comment by karmagongde** [comment]
I deleted sub-folders. Since there are two main texts in one volume. The folder marked 1. and 2.
1-dpe tshan sna tshogs 659-690 (range of text)~~460p (~~total page number)
No need to concern on ~~this.
Most of the BW images are duplicates. I deleted them.

**Comment by TBRC-Travis** [comment]
Thanks Karma.  I still see many subfolders with b&w images and corrupt images in them.  I've attached a list of subfolders that are still there.

[W3CN11633-subfolders.txt](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1749366/W3CN11633-subfolders.txt)

**Comment by karmagongde** [comment]
Now I see. These sub-folders need to be arrange according order. These are all created outline. 
Please see the outline. Looks like need to rename pages manual. 
![screen shot 2018-02-22 at 3 11 31 pm](https://user-images.githubusercontent.com/19337852/36561854-062b0904-17e3-11e8-9deb-d2e1381f3ffb.png)

**Comment by karmagongde** [comment]
I checked several folder from your subfolders list and several are empty.

**Comment by karmagongde** [comment]
All the folders organized.
