### ISSUE TITLE
W2PD17528 - images not available on the website

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#161]
https://www.tbrc.org/#!rid=W2PD17528

"This work has no scanned pages"

**Comment by karmagongde** [comment]
Do you have images of W2PD17528? Is it already renamed? If so, what is image group number? So that, I can try to solve the problem.

**Comment by TBRC-Travis** [comment]
The images are already synced to the archive.  Image group number is W2PD17528-I2PD20125

**Comment by karmagongde** [comment]
@TBRC-Travis I added volume map.

**Comment by TBRC-Travis** [comment]
Wonderful.  Looks good now.
