### ISSUE TITLE
W4PD5024 - URGENT - images not displayed on website; wrong image group number

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#164]
https://www.tbrc.org/#!rid=W4PD5024

Images are not showing up on the website due to incorrect image group number.

On the website it shows:  Volume 1 [I4PD5154]	
Page images not yet available for this Volume

But I synced the following image group numbers:
W4PD5024-I4PD5042
W4PD5024-I4PD5043
W4PD5024-I4PD5044
W4PD5024-I4PD5045
W4PD5024-I4PD5046

I'm guessing a new scan request needs to be created.

**Comment by karmagongde** [comment]
I fixed them the volume maps. Close the ticket. Thanks.

**Comment by TBRC-Travis** [comment]
Excellent.  Everything is showing up now.  Thanks!
