### ISSUE TITLE
W00KG017 - does not have a valid catalog record

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#175]
W00KG017 has images on disk in the archive but when you try to access the work on the website it doesn't load.  We need to create and/or fix the catalog record for this work.

This was flagged by the Internet Archive ingest process and needs to be resolved.  Thanks!

**Comment by karmagongde** [comment]
I fixed it. Please check again.

**Comment by TBRC-Travis** [comment]
It's showing up on the website now.  Thanks Karma.
