### ISSUE TITLE
W3CN2037 - images not showing up online

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#184]
W3CN2037 images are on disk but not showing up on the website

Catalog record and access information needs to be updated.

This was flagged as part of the Internet Archive ingest and needs to be resolved. Thanks!

**Comment by karmagongde** [comment]
fixed. Please close all the tickets which are done. Thank you.

**Comment by TBRC-Travis** [comment]
Looks good.  Thanks!
