### ISSUE TITLE
TML log-in problem

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#193]
@xristy Dear Chris,
TML of Dzongsar Khyentse Chokyi Lodro Institute library (DKCLI) is unable to log-in since November, 2017. Could you please reset they password so that they can able continue catalogue. 

I contact to Ngawang la at Dzongsar Library and he said, since November they TML is not working. The main issue is they can't log-in.

They user ID: dzongsarlibrary
Password: librarydzongsar

Thank you,
Karma

**Comment by xristy** [comment]
@karmagongde did you or Kelsang not have success resetting the password for dzongsarlibrary? I recall sometime last year showing Kelsang how to reset passwords since password reset requests are handled by you all.
