### ISSUE TITLE
duplicate image in vol. 90 of W4CZ5369

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#195]
these two images are the same:

https://www.tbrc.org/browser/ImageService?work=W4CZ5369&igroup=I1KG9216&image=79&first=1&last=578&fetchimg=yes

https://www.tbrc.org/browser/ImageService?work=W4CZ5369&igroup=I1KG9216&image=80&first=1&last=578&fetchimg=yes

**Comment by karmagongde** [comment]
@eroux @TBRC-Travis These two pages are identical. I deleted one. I also did images arrangement in all the volumes of W4CZ5369 in incoming/scans/ReadyToProcess/W4CZ5369. Travis, could you please rename and replace. Then I will finish outline of this work number. Thank you.
