### ISSUE TITLE
W4CZ5369 rename and re-sync

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#199]
@TBRC-Travis Hi Travis, would you please rename and re-sync W4CZ5369. I have removed all the unwanted pages in the beginning and today Adam informed the order error. I fixed that also. 
Located at incoming/scans/ReadyToProcess/W4CZ5369
Thank you.

**Comment by karmagongde** [comment]
@TBRC-Travis Hi Travis, When you get time to Sync images please rename and re-sync W4CZ5369. I removed all the unwanted pages in the beginning and today Adam informed the order error. I fixed that also. And the images in Partial folders need to be synced. There are the corrected images.
Located at incoming/scans/ReadyToProcess/W4CZ5369

**Comment by TBRC-Travis** [comment]
@karmagongde I've re-synced W4CZ5369.  Please take a look.  If the images look good now please go ahead and close the ticket.  Thanks.

https://www.tbrc.org/#!rid=W4CZ5369

**Comment by karmagongde** [comment]
@TBRC-Travis I checked and look fine. Thank you.
