### ISSUE TITLE
Review copyright works

### ISSUE THREAD

**Issue by jeffwallman** [BuddhistDigitalResourceCenter/library-issues#20]
Please review all currently copyright works and confirm the license and access policy for each.

Here is the spreadsheet

https://docs.google.com/spreadsheets/d/1lIgkcHKKcC_D9rtdU9u7ojtFEJ7j7jp2PllgcagvbCU/edit#gid=1035642989

**Comment by karmagongde** [comment]
Hi Jeff,
Lobsang la and I am currently reviewing and marking the license and access accordingly. Chozin la is fixing the outline errors, when she finished fixing the outlines, she will also work on this project. Chungdak la is traveling to Tibet tomorrow. We will complete reviewing at the end of this Month.
