### ISSUE TITLE
etext of W3JT13533

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#203]
@xristy Hi Chris, I looked for etext W3JT13533 in TBRCRS#/eTextsArchive and did not found it. Monk from Nepal requested for sman bla'i mdo chog bsdus pa bdud rtsi'i bum bzang by 'ju mi pham rnam rgyal rgya mtsho. They needed this text for zungzhug. Please help. Thank you.

**Comment by xristy** [comment]
@karmagongde I've uploaded **MiphamCW_LarungGar_W3JT13533** to **TBRCRS#/eTextsArchive**. I would suggest passing on the PDF. These volumes haven't been worked on since October 2014 and I was not able to create the searchable XML docs at that time.
