### ISSUE TITLE
pubinfo missing series information

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#211]
The following RIDs are missing series information in their pubinfo:

- [x] W1GS49554
- [x] W1GS49575
- [x] W1GS49915
- [x] W1GS50020

for example, [W1GS49554](https://www.tbrc.org/xmldoc?rid=W1KG6162) has

```xml
<work:info nodeType="series" parent="W20150"/>
```

while it should have

```xml
<work:info nodeType="series" number="2" numbered="true" parent="W20150"/>
```

this breaks the migration a bit for these records

**Comment by karmagongde** [comment]
I will modify and let you know.

**Comment by karmagongde** [comment]
I added selected series and added series number in publishedWork. Please check.

**Comment by eroux** [comment]
looks good, thanks!
