### ISSUE TITLE
new author records for Gretil import

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#213]
I'm starting to work on the initial import of data from [Gretil](http://gretil.sub.uni-goettingen.de/), Charles did a first pass on the titles and person names in [this doc](https://docs.google.com/spreadsheets/d/15frRQX7ZrOBtZG6GDNBpPFcC8BhPDdjDSaMwi1BZJ8Q/edit) but in order to perform the initial import I need some RIDs for the following authors:

- [ ] Amṛtākara see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/acatstvu.htm)
- [ ] Buddhaghoṣa see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/bghsic_u.htm)
- [ ] Mātṛceṭa see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/busto1_u.htm)
- [ ] Davuldeṇa Jñāneśvara Mahāsthavira see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/davyasou.htm)
- [ ] Jayarakṣita see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/jsphustu.htm)
- [ ] Jñānayaśas see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/jatkstau.htm)
- [ ] Kambalapada see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/knavslou.htm)
- [ ] Durvekamiśra see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/durdhpru.htm)
- [ ] Haribhadrasūri see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/bsa066_u.htm)
- [ ] Harivarman see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/hvsatssu.htm)
- [ ] Paṇḍitāśoka see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/bsa0554u.htm)
- [ ] Vidyākaraśānti see [this text](http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/vtrksopu.htm)
- [ ] Nāgasena see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/2_parcan/milindou.htm)
- [ ] Medhaṃkara see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/6_suanco/lokapp_u.htm)
- [ ] Kalyāniya see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/7_poe/telaka_u.htm)
- [ ] Chapaṭa Saddhammajotipāla see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/chkacsnu.htm)
- [ ] Piyadassī see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/padasa_u.htm)
- [ ] Dhammasenāpati Thera see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/dhkariku.htm)
- [ ] Mahāyasa Thera see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/mkacbheu.htm)
- [ ] Dhammarājaguru see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/saddab_u.htm)
- [ ] Saddhammasiri Thera see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/saddatbu.htm)
- [ ] Yasa Mahāthere [Mahāyasa] see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/gramm/yaskacsu.htm)
- [ ] Moggallāna Thera see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/lex/abhidh_u.htm)
- [ ] Saṅgharakkhita Thera see [this text](http://gretil.sub.uni-goettingen.de/gretil/2_pali/9_phil/rhet/subodh_u.htm)

Thank you

**Comment by karmagongde** [comment]
Hi Elie,
Librarians in the Cambridge office are professional in Tibetan and we work with Tibetan texts. Please send me the inquiry related with Tibetan Texts, creating and modifying catalog record, person, topic, place, outline issues. I will do my best to solve the problem.
The catalog record, person, topic, place which is in Sanskrit, Charles is the right person to ask. He is Sanskrit scholar of our organization. 
After each author, see this text, all are in Diacritic Sanskrit. Which I can't read. 
Sorry, I am not able to help on this one.
Karma

**Comment by eroux** [comment]
ok
