### ISSUE TITLE
duplicate outline node IDs

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#22]
- [ ] O1PD181215 has duplicate nodes O2DB757124CZ175796 and O2DB757124CZ175793
- [x] O1KG747 has duplicates O1KG7471AT345
- [ ] O9TAXTBRC201605 has duplicates O9TAXTBRC2016051KG23672
- [x] O1VI2 has duplicates O1VI2VI162
- [x] O2CZ10776 has duplicates O2CZ107763CZ77
- [x] O1LS2931 has duplicates O1LS29311LS2935

**Comment by karmagongde** [comment]
Hi Elie,
I had normalized all the checked outlines, O1PD181215 is still with Paldor la, He is finishing the outline, there are many volumes which are not outline at all.
But, O9TAXTBRC201605 is not a regular outline. This is BDRC subject classification.

**Comment by eroux** [comment]
Ok thank you!
