### ISSUE TITLE
error in P2246

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#220]
the record of P2246 states he is

> The individual at whose behest the rnam thar of Sangs rgyas rdo rje 'chang in the Shangs pa gser 'phreng ba written by Rmog-lcogs-pa Rin-chen-brtson-'grus.

but it seems to be a mistake, as the person who wrote the work is P3JT13498.

**Comment by eroux** [comment]
(the name of the author seems to be *rmog lcogs pa kun dga' 'od*)

**Comment by eroux** [comment]
The source of the info is [this text](https://www.tbrc.org/#library_work_ViewByOutline-O01DG1049095065%7CW23922), page 76

**Comment by eroux** [comment]
also in this page : https://www.tbrc.org/browser/ImageService?work=W23922&igroup=3537&image=56&first=1&last=788&fetchimg=yes

**Comment by eroux** [comment]
In brief, it's not clear who rmog lcogs pa kun dga' 'od is, there doesn't seem to be any known biography. He may not be P3JT13498 so it's probably best to have a new record for him. But this text:

![imageservice](https://user-images.githubusercontent.com/60868/49500586-540e0d00-f871-11e8-9168-c7b1a555043a.png)

(in vol 9) makes it clear that rmog lcogs pa kun dga' 'od and rmog lcog pa rin chen brtson 'grus are different.

**Comment by eroux** [comment]
Another source is W1PD45495 vol. 34 page indicated 259 (tbrc page 291):

https://www.tbrc.org/browser/ImageService?work=W1PD45495&igroup=I1PD84512&image=291&first=1&last=378&fetchimg=yes

which indicates that they were two distinct masters (of different times)

**Comment by karmagongde** [comment]
Hi Elie,
I am happy to make the correction according to your friend's suggestion. Since he is doing research on Shangpa Kagyu tradition, he has better knowledge on this topic. Would you please ask your friend please tell me the whole story again. One, I understand, I will make the correction. Sorry for asking again.

**Comment by eroux** [comment]
Ok, so basically the name "rmog lcogs pa kun dga' 'od" should be added to P3JT13498 and it should contain that he's the author of
   * https://www.tbrc.org/#library_work_ViewByOutline-O01DG1049094921%7CW23922
   * https://www.tbrc.org/#library_work_ViewByOutline-O01DG1049094922%7CW23922
   * https://www.tbrc.org/#library_work_ViewByOutline-O1KG4284C2O0010%7CW1KG4284

The identification of the author of these books and the person receiving the lineages (P3JT13498) is https://www.tbrc.org/#library_work_ViewByOutline-O01DG1049094921%7CW23922 page numbered 259 line 8 in the original.

Would that be ok?

**Comment by karmagongde** [comment]
I have added rmog lcogs pa kun dga' 'od on P3JT13498 record.

**Comment by eroux** [comment]
Thanks! can you add him as the author of the works I indicated?

**Comment by karmagongde** [comment]
The outlines of W23922 (11 vols) and W1KG4284 (2 vols) are created as a structured Outline. To finish more outline, we are creating a structured Outline first. Soon we start working on semantic Outline (detailed outline with author, topics etc.) and I will prioritize this two work numbers to be done in the beginning.

**Comment by eroux** [comment]
oh ok I didn't understand that, no problem
