### ISSUE TITLE
glitches in volumeMaps

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#31]
I found the following small glitches in the image lists:

- [x] [W21697](https://www.tbrc.org/#!rid=W21697) on property `archiveInfo/vols`: work claims it has `2` volumes while referencing `3` volumes in image groups
- [x] [W2CZ8093](https://www.tbrc.org/#!rid=W2CZ8093) on property `archiveInfo/vols`: work claims it has `1` volumes while referencing `2` volumes in image groups
- [x] [W1KG23417](https://www.tbrc.org/#!rid=W1KG23417) on property `archiveInfo/vols`: work claims it has `5` volumes while referencing `12` volumes in image groups
- [x] [W1PD512](https://www.tbrc.org/#!rid=W1PD512) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W1KG15965](https://www.tbrc.org/#!rid=W1KG15965) on property `archiveInfo/vols`: work claims it has `4` volumes while referencing `5` volumes in image groups
- [x] [W2DB4548](https://www.tbrc.org/#!rid=W2DB4548) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W20242](https://www.tbrc.org/#!rid=W20242) on property `archiveInfo/vols`: work claims it has `84` volumes while referencing `117` volumes in image groups
- [x] [W1KG3972](https://www.tbrc.org/#!rid=W1KG3972) on property `archiveInfo/vols`: work claims it has `1` volumes while referencing `2` volumes in image groups
- [x] [W20819](https://www.tbrc.org/#!rid=W20819) on property `archiveInfo/vols`: work claims it has `47` volumes while referencing `90` volumes in image groups
- [x] [W23909](https://www.tbrc.org/#!rid=W23909) on property `archiveInfo/vols`: work claims it has `3` volumes while referencing `4` volumes in image groups
- [x] [W1KG10720](https://www.tbrc.org/#!rid=W1KG10720) on property `archiveInfo/vols`: work claims it has `6` volumes while referencing `8` volumes in image groups
- [x] [W29636](https://www.tbrc.org/#!rid=W29636) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W29636](https://www.tbrc.org/#!rid=W29636) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W4CZ74453](https://www.tbrc.org/#!rid=W4CZ74453) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W00EGS1016719](https://www.tbrc.org/#!rid=W00EGS1016719) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W20821](https://www.tbrc.org/#!rid=W20821) on property `volume`: volume list has two or more image groups for volume `46`
- [x] [W20111](https://www.tbrc.org/#!rid=W20111) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W2DB4539](https://www.tbrc.org/#!rid=W2DB4539) on property `volume`: volume list has two or more image groups for volume `1`
- [x] [W1KG22268](https://www.tbrc.org/#!rid=W1KG22268) on property `archiveInfo/vols`: work claims it has `2` volumes while referencing `4` volumes in image groups
- [x] [W1PD133170](https://www.tbrc.org/#!rid=W1PD133170) on property `archiveInfo/vols`: work claims it has `1` volumes while referencing `8` volumes in image groups
- [x] [W1KG12536](https://www.tbrc.org/#!rid=W1KG12536) on property `archiveInfo/vols`: work claims it has `1` volumes while referencing `2` volumes in image groups
- [x] [W23635](https://www.tbrc.org/#!rid=W23635) on property `archiveInfo/vols`: work claims it has `4` volumes while referencing `9` volumes in image groups
- [x] [W1KG12113](https://www.tbrc.org/#!rid=W1KG12113) on property `archiveInfo/vols`: work claims it has `1` volumes while referencing `2` volumes in image groups
- [x] [W1KG24102](https://www.tbrc.org/#!rid=W1KG24102) on property `archiveInfo/vols`: work claims it has `7` volumes while referencing `9` volumes in image groups
- [x] [W1KG15927](https://www.tbrc.org/#!rid=W1KG15927) on property `archiveInfo/vols`: work claims it has `2` volumes while referencing `3` volumes in image groups
- [x] [W2DB20795](https://www.tbrc.org/#!rid=W2DB20795) on property `volume`: volume list has two or more image groups for volume `1`

**Comment by karmagongde** [comment]
Among the glitches in the image lists: 1. When work claims lower number and referencing is higher volume number are: When Librarians generate scan-request and knew that there should have such among of volumes and received only fewer volume. That is why different number are shown. Future we will change the number of work claimed one when we received the missing volumes.
2. Some image group numbers are manually added. That is why order is not in sequence or different initials (KG, JW). Does this make any issue in displaying the images on website?
3. W7335 image group order are not in the correct order. But the volume number order are in correct order.
4. Most of the Journal books, we generated lots of imageGroup number. Since every year the Journal will be published.
Please let me know to solve the problems.
Thank you.

**Comment by eroux** [comment]
I've updated the list with the real problems. The wrong values of `archiveInfos/vols` are not crucial, but it's quite important to fix the duplicate volume image groups...

**Comment by karmagongde** [comment]
Hi Elie,
I fixed all the listed ArchiveInfo volume number issues.
Please check W20821 which is not opening on website. loading......

**Comment by eroux** [comment]
Thanks! The xml of the volume map of W20821 looks weird, I think there has been a problem with the editing, but I'll fix it

**Comment by eroux** [comment]
W20821 has in fact been modified in a wrong way. It used to have the following map:

- ...
- vol 46 imagegroup I1KG14809
- vol 46 imagegroup I1KG14809
- vol 47 imagegroup I1KG14810
- vol 48 imagegroup I1KG14811
- ...

now it has

- ...
- vol 46 imagegroup I1KG14809
- vol 47 imagegroup I1KG14809
- vol 48 imagegroup I1KG14810
- vol 49 imagegroup I1KG14811
- ...

but `I1KG14809` is now referenced once for vol 46 and once for vol 47, which is even more wrong than the original data which was a simple duplication. Please fix it appropriately.

**Comment by karmagongde** [comment]
Now website opened the work W20821. So that, I can see the volume order and image group number.
I just fixed it.

**Comment by eroux** [comment]
Thanks!
