### ISSUE TITLE
image groups used in different works

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#33]
Some image groups are used in multiple works:

- [ ] `I3PD1094` referenced in `W2PD17384` and `W3PD1091`
- [ ] `I3PD1090` referenced in `W3PD989` and `W2PD17384`
- [ ] `I3PD1086` referenced in `W3PD989` and `W2PD17384`
- [ ] `I3PD1087` referenced in `W3PD989` and `W2PD17384`
- [ ] `I3PD1088` referenced in `W3PD989` and `W2PD17384`
- [ ] `I3PD1089` referenced in `W3PD989` and `W2PD17384`
- [ ] `I1PD105854` referenced in `W1PD105852` and `W1AC304`
- [ ] `I1KG10231` referenced in `W4JW5383` and `W30183`
- [ ] `I1KG10232` referenced in `W4JW5383` and `W30183`
- [ ] `I1KG10233` referenced in `W4JW5383` and `W30183`
- [ ] `I1KG10234` referenced in `W4JW5383` and `W30183`
- [ ] `I3PD1199` referenced in `W3PD988` and `W3PD994`
- [ ] `I3PD1209` referenced in `W3PD988` and `W1PD192038`
- [ ] `I3PD1210` referenced in `W3PD988` and `W1PD192038`
- [ ] `I3PD1212` referenced in `W3PD988` and `W3PD987`
- [ ] `I3PD1213` referenced in `W3PD988` and `W3PD987`
- [ ] `I3PD1214` referenced in `W3PD988` and `W3PD987`
- [ ] `I3PD1215` referenced in `W3PD988` and `W3PD987`
- [ ] `I3PD1216` referenced in `W3PD988` and `W3PD987`
- [ ] `I3PD1200` referenced in `W3PD988` and `W3PD994`
- [ ] `I3PD1201` referenced in `W3PD988` and `W3PD994`
- [ ] `I3PD1203` referenced in `W3PD988` and `W1PD159387`
- [ ] `I3PD1204` referenced in `W3PD988` and `W1PD159387`
- [ ] `I3PD1267` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1205` referenced in `W3PD988` and `W1PD159387`
- [ ] `I3PD1268` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1269` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1270` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1271` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1272` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1273` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1274` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1275` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1276` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1277` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1206` referenced in `W3PD988` and `W1PD159387`
- [ ] `I3PD1278` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1279` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1280` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1281` referenced in `W3PD988` and `W3PD983`
- [ ] `I3PD1207` referenced in `W3PD988` and `W1PD159387`
- [ ] `I3PD71` referenced in `W2PD17092` and `W1PD181145`
- [ ] `I3PD1126` referenced in `W2PD16865` and `W3PD1123`
- [ ] `I3PD1127` referenced in `W2PD16865` and `W3PD1123`
- [ ] `I3PD1125` referenced in `W2PD16865` and `W3PD1123`
- [ ] `I3PD1096` referenced in `W3PD1092` and `W2PD17384`
- [ ] `I3PD1097` referenced in `W3PD1092` and `W2PD17384`
- [ ] `I1KG570` referenced in `W4JW33624` and `W00KG010265`
- [ ] `I3PD1006` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1007` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1008` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1009` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1010` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1011` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1012` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1013` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1014` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1015` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1016` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1017` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1018` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1019` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1020` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1021` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1022` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1023` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1024` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1025` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1026` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1027` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1028` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1029` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1030` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1031` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1032` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1033` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1034` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1035` referenced in `W2PD17385` and `W2PD17386`
- [ ] `I3PD1037` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1038` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1039` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1040` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1041` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1042` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1043` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1044` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1045` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1046` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1047` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1048` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1049` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1050` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1051` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1052` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1053` referenced in `W2PD17385` and `W3PD1002`
- [ ] `I3PD1222` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1231` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1232` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1233` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1234` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1235` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1236` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1237` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1238` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1239` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1240` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1223` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1241` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1242` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1243` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1244` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1245` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1246` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1247` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1248` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1249` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1250` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1224` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1251` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1252` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1253` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1254` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1255` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1256` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1257` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1258` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1259` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1260` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1225` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1226` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1227` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1228` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1229` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1230` referenced in `W2PD17382` and `W3PD988`
- [ ] `I3PD1129` referenced in `W3PD889` and `W2PD16865`
- [ ] `I3PD1138` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1139` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1140` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1141` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1142` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1143` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1144` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1145` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1146` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1147` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1130` referenced in `W3PD889` and `W2PD16865`
- [ ] `I3PD1148` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1149` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1150` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1151` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1152` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1153` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1154` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1155` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1156` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1157` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1131` referenced in `W3PD889` and `W2PD16865`
- [ ] `I3PD1158` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1159` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1160` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1161` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1162` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1163` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1164` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1165` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1166` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1167` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1168` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1169` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1170` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1171` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1172` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1173` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1174` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1176` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1177` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1133` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1178` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1179` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1180` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1181` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1182` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1183` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1184` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1185` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1186` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1187` referenced in `W3PD889` and `W3PD1000`
- [ ] `I3PD1134` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1189` referenced in `W3PD889` and `W3PD445`
- [ ] `I3PD1190` referenced in `W3PD889` and `W3PD445`
- [ ] `I3PD1192` referenced in `W3PD889` and `W3PD887`
- [ ] `I3PD1193` referenced in `W3PD889` and `W3PD887`
- [ ] `I3PD1135` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1136` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1137` referenced in `W3PD889` and `W2PD17383`
- [ ] `I3PD1195` referenced in `W3PD999` and `W3PD889`
- [ ] `I3PD1196` referenced in `W3PD999` and `W3PD889`
- [ ] `I3PD1102` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1111` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1112` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1113` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1114` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1115` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1117` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1118` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1119` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1120` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1103` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1121` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1122` referenced in `W3PD1003` and `W2PD16865`
- [ ] `I3PD1104` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1105` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1106` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1107` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1108` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1109` referenced in `W3PD1003` and `W2PD17384`
- [ ] `I3PD1110` referenced in `W3PD1003` and `W2PD17384`

**Comment by karmagongde** [comment]
Fixed some image groups in two work numbers. Please check again and let me know any work numbers needed to be correction again. Thank you!

**Comment by eroux** [comment]
Thanks! You fixed most of them except for these two:

- [ ] [I3PD1209](https://www.tbrc.org/#!rid=I3PD1209) is referrenced in both [W1PD192038](https://www.tbrc.org/#!rid=W1PD192038) and [W3PD988](https://www.tbrc.org/#!rid=W3PD988) (indicates W1PD192038)
- [ ] [I3PD1210](https://www.tbrc.org/#!rid=I3PD1210) is referrenced in both [W1PD192038](https://www.tbrc.org/#!rid=W1PD192038) and [W3PD988](https://www.tbrc.org/#!rid=W3PD988) (indicates W1PD192038)

**Comment by karmagongde** [comment]
I fixed these two also.

**Comment by eroux** [comment]
thanks!
