### ISSUE TITLE
outline for W1KG1286

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#34]
A friend of mine made an outline for [W1KG1286](http://tbrc.org/#!rid=W1KG1286) in Excel. It's fairly small (40 parts) and is based on the page number of bdrc (taking into account the 2 scan request pages), so I think it should be easy to integrate. Here is the file:

[Karcha W1KG1286.xlsx](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1386709/Karcha.W1KG1286.xlsx)

Thank you!

**Comment by eroux** [comment]
As a side note, all the texts in the volume are about the Shangpa lineage, maybe it could be linked to this topic...

**Comment by karmagongde** [comment]
We Librarians will create outline for W1KG1286.

**Comment by karmagongde** [comment]
Hi Elie, 
Assigned Kelsang Lhamo to created outline for W1KG1286 and it is done. Outline number is O4CZ300336.
Best,
Karma

**Comment by eroux** [comment]
Thank you very much! A very few problems occur:

- in the first text, the text is about Vajradhara ([T1987](https://www.tbrc.org/#!rid=T1987)), not shAkya thub pa/ ([T1AT489](https://www.tbrc.org/#!rid=T1AT489))
- some titles end with `།` instead of `/`
- in the first title, `rnampar thar pa` should be `rnam par thar pa` (with a space)

**Comment by eroux** [comment]
Also, he proposes to add in the description of the work that:
- it is specifically Shangpa Kagyu
- it has many empowerments (more than instruction manuals)

**Comment by karmagongde** [comment]
I will check and fix the subject and other typos. As well as add more in cat info.

**Comment by karmagongde** [comment]
Hi Elie,
I fixed all the error you have suggested. Thank to your friend from me.
Best,
Karma

**Comment by eroux** [comment]
perfect, thank you!
