### ISSUE TITLE
outline for W4CZ5369

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#35]
To make the etexts/epubs more attractive, it would make a lot of sense to have an outline for [W4CZ5369](https://www.tbrc.org/#!rid=W4CZ5369), on which the eKangyur is based.

See #27 for information about why the past outline has been withdrawn.

Thank you,

**Comment by eroux** [comment]
will be handled on another channel, no need for a new outline in the current system

**Comment by karmagongde** [comment]
I have already outline for W4CZ5369. There is one page extra on every volume. So, I fixed them and asked Travis to re-sync.
Librarian are working on Outline on Thursdays and Fridays. Shall I ask them to stop creating New Outline on DLMS now onward until the new Channel?

**Comment by eroux** [comment]
Oh I see... other outlines can continue to be created, only the outlines of the Kangyur / Tengyur are (most probably) going to be created through another channel

**Comment by jeffwallman** [comment]
Karma-la, Elie is batch creating canonical outlines from Vienna.  Therefore, we should not be working on canonical outlines.  We can work on gsung 'bum and other multi-volume collections but not canon.
