### ISSUE TITLE
W30410 - missing many volumes

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#42]
This work has 20 volumes but only 3 image group folders here:

Incoming/scans/ReadyToProcess/Other/W30410

**Comment by karmagongde** [comment]
W30410 is a periodical journal. we received 3 volumes only. Therefore, there are 3 volumes images. reset are to be added after we get the images. <v. 2, 5, 6> see in publication info note.

**Comment by TBRC-Travis** [comment]
Ok.  We'll go ahead and process this.  Thanks.
