### ISSUE TITLE
W4CZ45303 - contains extra image subdirectories that need to be organized properly

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#55]
Incoming/scans/ReadyToProcess/Other/W4CZ45303

There are many volume folders which contain image subdirectories that need to be organized and copied into the main volume folder.  Here is the list of extra image subdirectories that need to be organized properly:

./W4CZ45303-I4CZ45331/04/falsch
./W4CZ45303-I4CZ45334/07/Ja_falsch
./W4CZ45303-I4CZ45336/09/Ta_falsch
./W4CZ45303-I4CZ45378/51/Cha_falsch
./W4CZ45303-I4CZ45379/52/Deckel
./W4CZ45303-I4CZ45387/60/Mini
./W4CZ45303-I4CZ45388/61/Mini
./W4CZ45303-I4CZ45391/64/Mini
./W4CZ45303-I4CZ45392/65/Mini
./W4CZ45303-I4CZ45394/67/Mini
./W4CZ45303-I4CZ45395/68/Mini
./W4CZ45303-I4CZ45397/70/Mini
./W4CZ45303-I4CZ45398/71/Mini
./W4CZ45303-I4CZ45402/75/A2
./W4CZ45303-I4CZ45402/75/A3
./W4CZ45303-I4CZ45402/75/A0
./W4CZ45303-I4CZ45402/75/A4
./W4CZ45303-I4CZ45405/78/mini
./W4CZ45303-I4CZ45406/79/mini
./W4CZ45303-I4CZ45407/80/Mini
./W4CZ45303-I4CZ45408/81/Chi_198-289_dup
./W4CZ45303-I4CZ45410/83/Nyi (Ti)
./W4CZ45303-I4CZ45410/83/Mini
./W4CZ45303-I4CZ45411/84/Mini
./W4CZ45303-I4CZ45411/84/Ti_rgyud
./W4CZ45303-I4CZ45412/85/Mini
./W4CZ45303-I4CZ45422/95/01_Ja
./W4CZ45303-I4CZ45422/95/2_Ja
./W4CZ45303-I4CZ45425/98/1_Tha
./W4CZ45303-I4CZ45425/98/2_Tha
./W4CZ45303-I4CZ45426/99/Deckel
./W4CZ45303-I4CZ45427/100/Schrott
./W4CZ45303-I4CZ45427/100/Da_Na
./W4CZ45303-I4CZ45429/102/Pha 01
./W4CZ45303-I4CZ45429/102/Pha 02
./W4CZ45303-I4CZ45430/103/01-Ba

**Comment by Klhamo** [comment]
W4CZ45303 Missing volume 6th from Vinayana. 
Rest of them done.
