### ISSUE TITLE
W4CZ45308 - contains many extra folders and images need to be consolidated and ordered properly

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#56]
Incoming/scans/ReadyToProcess/Other/W4CZ45308

Volume folders contain other directories that need to be consolidated into each main volume folder and ordered properly.  Please reorganize image files so they are in correct order and all under the image group directory in proper structure.

Here are the extra folders that need to be consolidated and organized into the main volume folders:

./W4CZ45308-I4CZ75430/01/1
./W4CZ45308-I4CZ75430/01/continually
./W4CZ45308-I4CZ75431/02/continually
./W4CZ45308-I4CZ75431/02/01
./W4CZ45308-I4CZ75432/03/A
./W4CZ45308-I4CZ75433/04/A
./W4CZ45308-I4CZ75433/04/B continually
./W4CZ45308-I4CZ75434/05/A
./W4CZ45308-I4CZ75434/05/continually
./W4CZ45308-I4CZ75448/19/02
./W4CZ45308-I4CZ75448/19/01
./W4CZ45308-I4CZ75450/21/a
./W4CZ45308-I4CZ75454/25/a
./W4CZ45308-I4CZ75454/25/continually
./W4CZ45308-I4CZ75457/28/a
./W4CZ45308-I4CZ75457/28/b continually
./W4CZ45308-I4CZ75457/28/continually
./W4CZ45308-I4CZ75458/29/a
./W4CZ45308-I4CZ75459/30/A
./W4CZ45308-I4CZ75459/30/b
./W4CZ45308-I4CZ75459/30/c
./W4CZ45308-I4CZ75460/31/A
./W4CZ45308-I4CZ75461/32/A
./W4CZ45308-I4CZ75461/32/c
./W4CZ45308-I4CZ75462/33/1
./W4CZ45308-I4CZ75462/33/ 02 continually
./W4CZ45308-I4CZ75462/33/04 continually
./W4CZ45308-I4CZ75462/33/03 continually
./W4CZ45308-I4CZ75463/34/037 mDo Tha 1
./W4CZ45308-I4CZ75463/34/038 mDo Tha 2
./W4CZ45308-I4CZ75464/35/039 mDo Da 1
./W4CZ45308-I4CZ75464/35/040 mDo Da 2
./W4CZ45308-I4CZ75464/35/041 mDo Da 3
./W4CZ45308-I4CZ75465/36/042 mDo Na 1
./W4CZ45308-I4CZ75465/36/043 mDo Na 2
./W4CZ45308-I4CZ75465/36/044 mDo Na 3
./W4CZ45308-I4CZ75466/37/045 mDo Pa 1
./W4CZ45308-I4CZ75466/37/046 mDo Pa 2
./W4CZ45308-I4CZ75466/37/047 mDo Pa 3
./W4CZ45308-I4CZ75467/38/047 mDo Pha 1
./W4CZ45308-I4CZ75467/38/049 mDo Pha 2
./W4CZ45308-I4CZ75468/39/050 mDo Ma 1
./W4CZ45308-I4CZ75468/39/051 mDo Ma 2
./W4CZ45308-I4CZ75468/39/052 mDo Ma 3
./W4CZ45308-I4CZ75469/40/053 mDo Tsa 1
./W4CZ45308-I4CZ75469/40/054 mDo Tsa 2
./W4CZ45308-I4CZ75469/40/055 mDo Tsa 3
./W4CZ45308-I4CZ75469/40/056 mDo Tsa 4
./W4CZ45308-I4CZ75470/41/057 mDo Tsha 1
./W4CZ45308-I4CZ75470/41/058 mDo Tsha 2
./W4CZ45308-I4CZ75470/41/059 mDo Tsha 3
./W4CZ45308-I4CZ75470/41/059 mDo Tsha 4
./W4CZ45308-I4CZ75471/42/060 mDo Dza 1
./W4CZ45308-I4CZ75471/42/061 mDo Dza 2
./W4CZ45308-I4CZ75471/42/062 mDo Dza 3
./W4CZ45308-I4CZ75472/43/063 mDo Wa 1
./W4CZ45308-I4CZ75472/43/064 mDo Wa 2
./W4CZ45308-I4CZ75472/43/065 mDo Wa 3
./W4CZ45308-I4CZ75472/43/066 mDo Wa 4
./W4CZ45308-I4CZ75473/44/067 mDo Zha 1
./W4CZ45308-I4CZ75473/44/068 mDo Zha 2
./W4CZ45308-I4CZ75473/44/069 mDo Zha 3
./W4CZ45308-I4CZ75474/45/070 mDo Za 1
./W4CZ45308-I4CZ75474/45/071 mDo Za 2
./W4CZ45308-I4CZ75475/46/072 mDo 'a 1
./W4CZ45308-I4CZ75475/46/073 mDo 'a 2
./W4CZ45308-I4CZ75475/46/074 mDo 'a 3
./W4CZ45308-I4CZ75475/46/075 mDo 'a 4
./W4CZ45308-I4CZ75476/47/076 mDo Ya 1
./W4CZ45308-I4CZ75476/47/077 mDo Ya 2
./W4CZ45308-I4CZ75476/47/078 mDo Ya 3
./W4CZ45308-I4CZ75476/47/079 mDo Ya 4
./W4CZ45308-I4CZ75476/47/080 mDo Ya 5
./W4CZ45308-I4CZ75477/48/081 mDo Ra 1
./W4CZ45308-I4CZ75477/48/082 mDo Ra 2
./W4CZ45308-I4CZ75477/48/083 mDo Ra 3
./W4CZ45308-I4CZ75478/49/084 mDo La 1
./W4CZ45308-I4CZ75478/49/085 mDo La 2
./W4CZ45308-I4CZ75478/49/086 mDo La 3
./W4CZ45308-I4CZ75478/49/087 mDo La 4
./W4CZ45308-I4CZ75479/50/088 mDo Sha 1
./W4CZ45308-I4CZ75479/50/089 mDo Sha 2
./W4CZ45308-I4CZ75479/50/090 mDo Sha 3
./W4CZ45308-I4CZ75480/51/091 mDo Sa 1
./W4CZ45308-I4CZ75480/51/092 mDo Sa 2
./W4CZ45308-I4CZ75480/51/093 mDo Sa 3
./W4CZ45308-I4CZ75481/52/094 mDo Ha 1
./W4CZ45308-I4CZ75481/52/095 mDo Ha 2
./W4CZ45308-I4CZ75482/53/096 mDo A 1
./W4CZ45308-I4CZ75482/53/097 mDo A 2
./W4CZ45308-I4CZ75482/53/098 mDo A 3
./W4CZ45308-I4CZ75482/53/099 mDo A 4
./W4CZ45308-I4CZ75483/54/100 mDo Gi 1
./W4CZ45308-I4CZ75483/54/101 mDo Gi 2
./W4CZ45308-I4CZ75483/54/102 mDo Gi 3
./W4CZ45308-I4CZ75483/54/103 mDo Gi supp
./W4CZ45308-I4CZ75484/55/104 mDo Ci 1
./W4CZ45308-I4CZ75484/55/105 mDo Ci 2
./W4CZ45308-I4CZ75484/55/106 mDo Ci 3
./W4CZ45308-I4CZ75484/55/107 mDo Ci 4
./W4CZ45308-I4CZ75484/55/108 mDo Ci 5
./W4CZ45308-I4CZ75485/56/109 mDo Chi 1
./W4CZ45308-I4CZ75485/56/110 mDo Chi 2
./W4CZ45308-I4CZ75485/56/111 mDo Chi 3
./W4CZ45308-I4CZ75486/57/112 mDo Ji 1
./W4CZ45308-I4CZ75486/57/113 mDo Ji 2
./W4CZ45308-I4CZ75486/57/114 mDo Ji 3
./W4CZ45308-I4CZ75486/57/115 mDo Ji 4
./W4CZ45308-I4CZ75487/58/116 mDo Ti 1
./W4CZ45308-I4CZ75487/58/117 mDo Ti 2
./W4CZ45308-I4CZ75487/58/118 mDo Ti 3
./W4CZ45308-I4CZ75488/59/119 mDo Thi 1
./W4CZ45308-I4CZ75488/59/120 mDo Thi 2
./W4CZ45308-I4CZ75488/59/121 mDo Thi 3
./W4CZ45308-I4CZ75489/60/AA
./W4CZ45308-I4CZ75489/60/c
./W4CZ45308-I4CZ75489/60/d
./W4CZ45308-I4CZ75489/60/e
./W4CZ45308-I4CZ75489/60/b
./W4CZ45308-I4CZ75490/61/142 rGyud Kha (10a)
./W4CZ45308-I4CZ75490/61/143 rGyud Kha (10b)
./W4CZ45308-I4CZ75490/61/143 rGyud Kha (10b)/Kha 2_A
./W4CZ45308-I4CZ75490/61/143 rGyud Kha (10b)/Kha 2_B
./W4CZ45308-I4CZ75491/62/144 rGyud Ga (10c)
./W4CZ45308-I4CZ75491/62/145 rGyud Ga (10d)
./W4CZ45308-I4CZ75492/63/146 rGyud Nga (11)
./W4CZ45308-I4CZ75492/63/146 rGyud Nga (11)/Nga 1-A
./W4CZ45308-I4CZ75492/63/147 rGyud Nga (12)
./W4CZ45308-I4CZ75492/63/147 rGyud Nga (12)/A
./W4CZ45308-I4CZ75492/63/147 rGyud Nga (12)/B
./W4CZ45308-I4CZ75492/63/148 rGyud Nga (13)
./W4CZ45308-I4CZ75492/63/176 rNying rgyud Nga (14)
./W4CZ45308-I4CZ75492/63/176 rNying rgyud Nga (14)/A
./W4CZ45308-I4CZ75493/64/149 rGyud Ca (16)
./W4CZ45308-I4CZ75493/64/149 rGyud Ca (16)/Ca 1-A
./W4CZ45308-I4CZ75493/64/149 rGyud Ca (16)/Ca 1-B
./W4CZ45308-I4CZ75493/64/150 rGyud Ca (20)
./W4CZ45308-I4CZ75493/64/151 rGyud Ca (21)
./W4CZ45308-I4CZ75493/64/152 rGyud Ca (22)
./W4CZ45308-I4CZ75493/64/152 rGyud Ca (22)/Ca 4-A
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)/Cha 1-A
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)/Cha 1-B
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)/Cha 1-C
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)/Cha 1-D
./W4CZ45308-I4CZ75494/65/153 rGyud Cha (15)/Cha 1-x
./W4CZ45308-I4CZ75494/65/154 rGyud Cha (17)
./W4CZ45308-I4CZ75494/65/155 rGyud Cha (18)
./W4CZ45308-I4CZ75495/66/177rNying rgyud Ja (29)
./W4CZ45308-I4CZ75496/67/156 rGyud Nya (23)
./W4CZ45308-I4CZ75496/67/157 rGyud Nya (24)
./W4CZ45308-I4CZ75496/67/158 rGyud Nya (24)x
./W4CZ45308-I4CZ75496/67/159 rGyud Nya (25)
./W4CZ45308-I4CZ75496/67/160 rGyud Nya (26)
./W4CZ45308-I4CZ75497/68/161 rGyud Ta (27)
./W4CZ45308-I4CZ75497/68/162 rGyud Ta (28)
./W4CZ45308-I4CZ75498/69/163 rGyud Tha (30)
./W4CZ45308-I4CZ75498/69/164 rGyud Tha (31)
./W4CZ45308-I4CZ75498/69/165 rGyud Tha (33)
./W4CZ45308-I4CZ75498/69/166 rGyud Tha (38)
./W4CZ45308-I4CZ75499/70/167 rGyud Da (01)
./W4CZ45308-I4CZ75500/71/168 rGyud Na (02)
./W4CZ45308-I4CZ75500/71/169 rGyud Na (03)
./W4CZ45308-I4CZ75501/72/170 rGyud Pha (32)
./W4CZ45308-I4CZ75501/72/171 rGyud Pha (34)
./W4CZ45308-I4CZ75501/72/172 rGyud Pha (35)
./W4CZ45308-I4CZ75502/73/173 rGyud Ba (36)
./W4CZ45308-I4CZ75502/73/173 rGyud Ba (36)/A
./W4CZ45308-I4CZ75502/73/173 rGyud Ba (36)/B
./W4CZ45308-I4CZ75503/74/174 rGyud Ma (37)
./W4CZ45308-I4CZ75504/75/175 rGyud Tsa (04)
./W4CZ45308-I4CZ75505/76/185 gZungs  ohne (41)
./W4CZ45308-I4CZ75506/77/179 gZungs Kha (40)
./W4CZ45308-I4CZ75507/78/180 gZungs Ga 1 (10d)
./W4CZ45308-I4CZ75507/78/181 gZungs Ga 2 (10d)
./W4CZ45308-I4CZ75507/78/182 gZungs Ga 3 (10d)

**Comment by jeffwallman** [comment]
What do you need my help on?  Seems straight forward to rename and resize.

**Comment by karmagongde** [comment]
@jeffwallman Sorry, I am assigning Chozin la, but clicked on you email by mistake.

**Comment by TBRC-Travis** [comment]
I've added the full list of folder names that need to be consolidated and re-organized.

**Comment by Klhamo** [comment]
All set.

**Comment by TBRC-Travis** [comment]
This still needed quite a bit of organizing but I've taken care of it.
