### ISSUE TITLE
license / access oddities

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#59]
Some works have some license / access combinations that seem strange:

- [x] W8LS18463 has license `ccby` and access `fairUse`
- [x] W1KG13116 has license `ccby` and access `fairUse`
- [x] W3PD188 has license `ccby` and access `fairUse`
- [x] W20418 has license `ccby` and access `fairUse`
- [x] W1AC406 has license `ccby` and access `fairUse`
- [x] W1AC407 has license `ccby` and access `fairUse`
- [x] W1KG16785 has license `ccby` and access `fairUse`
- [x] W3CN3341 has license `ccby` and access `fairUse`
- [x] W3CN6742 has license `ccby` and access `fairUse`
- [x] W1GS66314 has license `ccby` and access `fairUse`
- [x] W3CN4663 has license `ccby` and access `fairUse`
- [x] W2PD19446 has license `ccby` and access `fairUse`
- [x] W4CZ296777 has license `copyrighted` and access `openAccess`

my understanding is that they all should be moved to `copyrighted` + `fairUse`.

**Comment by karmagongde** [comment]
That is right, all the access fairUse should be license by copyright. The work number W4CZ296777 is copyright and access should be fairUse.
Can you able to change them OR do you want me to correct them manually. Please let me know.

**Comment by eroux** [comment]
well, I don't really have an automatic method for this kind of things, and I have almost no experience in running the DLMS, so if you could change them that would be more efficient I think... really not a high priority though.

**Comment by karmagongde** [comment]
I will fix them. And let you know when I am done.

**Comment by karmagongde** [comment]
@eroux 
I fixed all the license issues.

**Comment by eroux** [comment]
thank you!
