### ISSUE TITLE
O3JT5542 has duplicate Node RIDs

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/library-issues#63]
When visiting

>  dri med 'od zer . "ku mA rA dza la rtogs pa phul ba/." In gsung 'bum/_dri med 'od zer/ ?dpal brtsegs/ mes po'i shul bzhag?. TBRC W1KG4884. 24: 318 - 322. pe cin/: krung go'i bod rig pa dpe skrun khang /, 2009. http://tbrc.org/link?RID=O3JT5542|O2CN67002CN73712CN85532CN86352CN86512CN86902CN88802CN91782CN91802CN91811PD121515$W1KG4884

in O3JT5542, I'm getting an error because there are three nodes with the same RID and this seems to be true of all of the items under volume 24.

**Comment by karmagongde** [comment]
@xristy Could you please send me those error nodes RID with title of the texts, It will be easy to find the exact RID so that I can fix them. Thank you.

**Comment by xristy** [comment]
as I indicated, all the nodes in volume 24. One of the nodes is included in the original message of the issue:

    O2CN67002CN73712CN85532CN86352CN86512CN86902CN88802CN91782CN91802CN91811PD121515

**Comment by karmagongde** [comment]
I had just new outlined for volume 24 and published.

**Comment by xristy** [comment]
thanks
