### ISSUE TITLE
W8LS17921 | W8LS17922 | W8LS17925 - scanned improperly, text goes off the page

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/library-issues#68]
These 3 works were scanned incorrectly and the text goes off the page.  These works need to be marked "Restricted by Quality".

@karmagongde

**Comment by karmagongde** [comment]
@TBRC-Travis Lobsang la has already marked Restricted by Quality for these three work numbers.

**Comment by TBRC-Travis** [comment]
Thanks!
