### ISSUE TITLE
wrong copyright on W29329

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#75]
[W29329](https://www.tbrc.org/#!rid=W29329) is a recent work, it is not in the public domain. Please mark it as copyrighted.

**Comment by karmagongde** [comment]
This Tibetan-Chinese dictionary, work number W29329 is published in 1985. It is also released in CTC 11. The books in which did not mention of copyright, BDRC marked Temporarily Restricted for 3 years from the year of publishing and then after we marked as open access.

**Comment by eroux** [comment]
(closing as it will be addressed in a broader reflection)
