### ISSUE TITLE
importing Tohoku catalogue

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#87]
It would be useful to import [this Tohoku catalogue](http://eroux.fr/Tohoku2.pdf), as we're using it in our data

**Comment by karmagongde** [comment]
Thank you for Tohoku catalogue. I have download both to catalog and add to our archive.

**Comment by karmagongde** [comment]
We have cataloged the " a complete catalogue of the tibetan buddhist cannons" W1PD95677.

**Comment by xristy** [comment]
I've "cleaned" up the PDF of the catalogue and OCR'd it; however, the OCR is monolingual so only the English-like parts make any sense and then the diacritics are either ignored or create strange results. I suppose that I could OCR in Chinese and perhaps Japanese and try to extract fragments. 

Anyway the result of my day's labor is [BUDA/Partners/Canon/Tohoku 西蔵撰述佛典目録 - m017e002t7.5x10.5f.pdf](https://drive.google.com/open?id=15HJuCJGyu6_zWrcGwVSBR-25wOe9zQvB)

It might be worthwhile spending some time on W1PD95677.

**Comment by karmagongde** [comment]
Here is work number W1KG13833 for a catalogue of the tohoku university collection of tibetan works on buddhism. The image is uploaded on Incoming/scans/ReadyToProcess/W1KG13833

**Comment by xristy** [comment]
I've renamed the version on Google drive @ BUDA/Partners/Canon/ to

    kanakura, et al - Tohoku Catalogue of Tibetan Buddhist Works - 1953 - W1KG13833.pdf

This version has corrections to the front matter and bookmark navigation in the PDF.

It is desirable that this version is the one that is processed.

**Comment by karmagongde** [comment]
I uploaded same cleaned and corrected image by Chris.

**Comment by xristy** [comment]
I've uploaded

    ui, et al - Tohoku Catalogue of the Tibetan Buddhist Canons - W1PD95677.pdf

to BUDA/Partners/Canon/. It is cleaned up and ocr'd but as with W1KG13833 the multilingual nature is an impediment as was the original scan.

It would be great if the original could be found and rescanned.

**Comment by karmagongde** [comment]
We searched the hardcopy of the both the Tohoku catalogs in our office and we did not found it.

**Comment by eroux** [comment]
There is another scan of the Tohoku KaTen catalogue [here](http://prajnaquest.fr/downloads/BookofDzyan/Tohoku%20Catalogue%20of%20Tibetan%20Buddhist%20Canons.pdf), I don't know if it's better for the OCR or not

**Comment by xristy** [comment]
Indeed I have that version on my system. I worked with the W1PD95677 since it included the index and was scanned 1-up. The prajnaquest scan is 2-up and is better scan quality but requires additional processing to split to 1-up.

**Comment by xristy** [comment]
I've uploaded the prajnaquest version to:

    ui, et al - Tohoku Catalogue of the Tibetan Buddhist Canons - prajnaquest.pdf

to BUDA/Partners/Canon/. This version is much cleaner than W1PD95677; however, it contains only a 3 page index rather than the 123 pp Catalogue-Index contained in W1PD95677.

**Comment by xristy** [comment]
I think this issue is done now
